### ISSUE TITLE
In an imgfy search the text is cut off

### ISSUE THREAD

**Issue by FlorianJS** [AdriBloober/DiscordSearchBot#57] opened 2020-05-07 21:54 UTC
**Describe the bug**
In an imgfy search the text is cut off

**To Reproduce**
§lmgtfy Open a File in Java

**Expected behavior**
Bot generates URL for just open
https://lmgtfy.com/?q=Open
![DeepinBildschirmfoto_Bereich auswählen_20200507235405](https://user-images.githubusercontent.com/54689374/81348256-117fde00-90be-11ea-8fb3-24a78e447cd7.png)

**Screenshots**

**Environment**
Not self hostet
**Additional context**
No additional context

**Comment by AdriBloober** [comment] 2020-05-07 21:56
Duplicate of https://github.com/AdriBloober/DiscordSearchBot/issues/55

**Closed by AdriBloober** 2020-05-07 21:56 UTC
Labels: duplicate
